name: Release
on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Bump version and push tag
              id: bump-and-tag
              uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
                PRERELEASE: true

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build
              run: | 
                  npm install
                  npm run build

            # TODO: Update Manifest

            - name: Zip Files
              working-directory: ./build
              run: zip -r ./pf2e-heroic-crafting.zip ./*

            - name: Create Version Release
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  name: ${{ steps.bump-and-tag.new-tag }}
                  allowUpdates: false
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./build/module.json,./build/pf2e-heroic-crafting.zip"
                  tag: ${{ steps.bump-and-tag.new-tag }}
